# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: 'fhir_dbt_utils_integration_tests'
version: '1.0.0'
require-dbt-version: '>=1.3.0'
config-version: 2
profile: 'fhir_dbt_utils'

target-path: "{{ env_var('DBT_TARGET_PATH', 'target') }}"
packages-install-path: "{{ env_var('DBT_PACKAGES_INSTALL_PATH', 'dbt_packages') }}"
log-path: "{{ env_var('DBT_LOG_PATH', 'logs') }}"

clean-targets:
  - "{{ env_var('DBT_TARGET_PATH', 'target') }}"
  - "{{ env_var('DBT_PACKAGES_INSTALL_PATH', 'dbt_packages') }}"
  - "{{ env_var('DBT_LOG_PATH', 'logs') }}"

dispatch:
  - macro_namespace: 'fhir_dbt_utils'
    search_order: ['fhir_dbt_utils_integration_tests', 'fhir_dbt_utils']

vars:
  organization: "Synthea"  # Name of the organization or business unit which owns the FHIR data. Used for titles in the analytics reports. [string]
  database: "bigquery-public-data"  # Name of the Google Cloud project that contains the BigQuery data. Used to connect to your FHIR data. [string]
  schema: "fhir_synthea"  # Name of the BigQuery dataset storing the FHIR data. Used to connect to your FHIR data. [string]
  fhir_version: "STU3"  # Version of FHIR that your data conforms to. [string]
  snake_case_fhir_tables: TRUE  # TRUE if your FHIR database tables are in snake case (e.g. allergy_intolerance). [boolean]
  timezone_default: "America/New_York"  # Default time zone for this dataset. The IANA time-zone name. For example, "Europe/London". [string]
  null_values: []  # List of string values to be considered as missing data when evaluating whether a field is recorded by has_value macro. [list]
  snapshot_date: "2023-01-01"  # Date on which to evaluate patient membership of cohort. If not set, the default will evaluate membership as of today using CURRENT_DATE(). Use format: "YYYY-MM-DD". [string]